### ISSUE TITLE
ExoPlayer Support

### ISSUE THREAD

**Issue by casajavi** [hola/android_sdk#1]
Hello, 
I am using the exoplayer in my project and would like to use Hola CDN. Is there any support for this ? 
Thanks!

**Comment by voidchai** [comment]
Hello,
we are going to add ExoPlayer support (for HLS videos) to SDK. At the moment, ExoPlayer isn't supported.

**Comment by casajavi** [comment]
Is there a plan to add it for DASH videos ?
